# Generated by Django 2.0.7 on 2018-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='turnover',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
    ]
