# Generated by Django 2.0.7 on 2018-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180706_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='collection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='net_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='turnover',
        ),
        migrations.AddField(
            model_name='product',
            name='functions',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='glass',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='strap',
            field=models.CharField(default='', max_length=25),
        ),
    ]
