# Generated by Django 2.0.7 on 2018-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='case',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='functions',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='glass',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='strap',
            field=models.CharField(default='', max_length=35),
        ),
    ]
